default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ror_basics_development
test:
  <<: *default
  database: ror_basics_test
production:
  <<: *default
  database: my_projec_7_production
  username: my_projec_7
  password: <%= ENV["MY_PROJEC_7_DATABASE_PASSWORD"] %>
